#!/bin/bash 
#PBS -N unialigner_test
#PBS -q batch 
#PBS -d /home/sjwan/ESA/
#PBS -o /home/sjwan/ESA/workflow/6_test_unialigner/unialigner_test.log 
#PBS -e /home/sjwan/ESA/workflow/6_test_unialigner/unialigner_test.error 
#PBS -l nodes=1:ppn=28

source ~/miniconda3/etc/profile.d/conda.sh
conda activate gcc9

unialigner=/home/sjwan/tools/unialigner/tandem_aligner/build/bin/tandem_aligner 
# first=/home/sjwan/ESA/hifiasm/ESA.samples/JPZ0325/JPZ0325.hap1.fa
first=/home/sjwan/ESA/reference/chm13v2.0.Y.sub.fa
second=/home/sjwan/ESA/reference/chm13v2.0.Y.fa
output=/home/sjwan/ESA/workflow/6_test_unialigner/output/JPZ30225

$unialigner --first $first --second $second -o $output
